FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY ./build /var/www

RUN chown root:nginx -R /usr/share/nginx
RUN chown root:nginx -R /var/cache/nginx
RUN chown root:nginx -R /var/run
RUN chown root:nginx -R /var/www
